// Movie Cache Action Types
export const FETCH_MOVIE_DETAIL_REQUEST = 'FETCH_MOVIE_DETAIL_REQUEST';
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
export const FETCH_MOVIE_DETAIL_FAILURE = 'FETCH_MOVIE_DETAIL_FAILURE';
export const CLEAR_MOVIE_CACHE = 'CLEAR_MOVIE_CACHE';
export const REMOVE_FROM_CACHE = 'REMOVE_FROM_CACHE';

// Movie Details Action Types
export const FETCH_MOVIE_FULL_DETAILS_REQUEST = 'FETCH_MOVIE_FULL_DETAILS_REQUEST';
export const FETCH_MOVIE_FULL_DETAILS_SUCCESS = 'FETCH_MOVIE_FULL_DETAILS_SUCCESS';
export const FETCH_MOVIE_FULL_DETAILS_FAILURE = 'FETCH_MOVIE_FULL_DETAILS_FAILURE';
export const FETCH_MORE_REVIEWS_REQUEST = 'FETCH_MORE_REVIEWS_REQUEST';
export const FETCH_MORE_REVIEWS_SUCCESS = 'FETCH_MORE_REVIEWS_SUCCESS';
export const FETCH_MORE_REVIEWS_FAILURE = 'FETCH_MORE_REVIEWS_FAILURE';
export const CLEAR_CURRENT_MOVIE = 'CLEAR_CURRENT_MOVIE';
