// Movie Details Action Types
export const FETCH_MOVIE_FULL_DETAILS_REQUEST = 'FETCH_MOVIE_FULL_DETAILS_REQUEST';
export const FETCH_MOVIE_FULL_DETAILS_SUCCESS = 'FETCH_MOVIE_FULL_DETAILS_SUCCESS';
export const FETCH_MOVIE_FULL_DETAILS_FAILURE = 'FETCH_MOVIE_FULL_DETAILS_FAILURE';
export const FETCH_MORE_REVIEWS_REQUEST = 'FETCH_MORE_REVIEWS_REQUEST';
export const FETCH_MORE_REVIEWS_SUCCESS = 'FETCH_MORE_REVIEWS_SUCCESS';
export const FETCH_MORE_REVIEWS_FAILURE = 'FETCH_MORE_REVIEWS_FAILURE';
export const CLEAR_CURRENT_MOVIE = 'CLEAR_CURRENT_MOVIE';
